# Generated by Django 4.0.4 on 2022-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='csv_files/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(default='123456', max_length=6)),
                ('cnpj', models.CharField(default='11223334444555', max_length=15)),
                ('razao_social', models.CharField(default='razao_social', max_length=100)),
                ('nome_fantasia', models.CharField(default='nome_fantasia', max_length=100)),
                ('modalidade', models.CharField(default='modalidae', max_length=100)),
                ('logradouro', models.CharField(default='logradouro', max_length=100)),
                ('numero', models.CharField(default='numero', max_length=100)),
                ('complemento', models.CharField(default='complemento', max_length=100)),
                ('bairro', models.CharField(default='bairro', max_length=100)),
                ('cidade', models.CharField(default='cidade', max_length=100)),
                ('uf', models.CharField(default='uf', max_length=100)),
                ('cep', models.CharField(default='cep', max_length=100)),
                ('ddd', models.CharField(default='ddd', max_length=100)),
                ('telefone', models.CharField(default='telefone', max_length=100)),
                ('fax', models.CharField(default='fax', max_length=100)),
                ('endereco_eletronico', models.CharField(default='endereco_eletronico', max_length=100)),
                ('representante', models.CharField(default='representante', max_length=100)),
                ('cargo_representante', models.CharField(default='cargo_representante', max_length=100)),
                ('data_registro_ans', models.DateField(default='1/1/2001')),
            ],
        ),
    ]
