# Generated by Django 4.0.4 on 2022-05-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saude', '0002_csvfiles_delete_fileuploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroempresa',
            name='nome_fantasia',
            field=models.CharField(default='sem_nome_fantasia', max_length=100),
        ),
        migrations.AlterField(
            model_name='registroempresa',
            name='razao_social',
            field=models.CharField(default='sem_razao_social', max_length=100),
        ),
    ]
